stages:
  - build
  - deploy

variables:
  FLY_API_TOKEN: $FLY_API_TOKEN
  FLY_APP_NAME: $FLY_APP_NAME # This should be dynamic based on the app name generated
  DOCKER_IMAGE: "registry.fly.io/$FLY_APP_NAME:latest"

build_and_push:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo $FLY_API_TOKEN | docker login -u "x" --password-stdin registry.fly.io
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main
